### ISSUE TITLE
How to get the aligned person data after the alignment network?

### ISSUE THREAD

**Issue by zengqixun12** [layumi/Pedestrian_Alignment#10]
I want to see the dataset after the alignment network ...but there is only some gifs without data output..

**Comment by layumi** [comment]
Hi @zengqixun12 
Sorry for the late response.
Actually, I extracted the affine parameters (predicted) and apply them to the input image.
I will find the code and upload it.

**Comment by layumi** [comment]
You may find the code in
https://github.com/layumi/Pedestrian_Alignment/tree/master/show_stn
