### ISSUE TITLE
关于imagenet加载模型后的transform的问题

### ISSUE THREAD

**Issue by sillytheif** [layumi/Pedestrian_Alignment#17]
哲东大佬，train.pyz中，关于对图片进行的调整中，transform.Normalzie里，给的均值和方差参数似乎与imagenet中图片的均值和方差不一样耶，这点应该会对结果有影响吧.......

**Comment by layumi** [comment]
Hi @sillytheif 
你问的是我另外一个代码的问题？
我使用的是 http://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html#training-the-model 里面的均值。

**Comment by sillytheif** [comment]
哦哦 对的.....那是我以前搞错了.....我原来下的代码和标准的不太一样.....谢谢大佬
