### ISSUE TITLE
Some questions in dagnn.AffineGridGenerator and dagnn.BilinearSampler

### ISSUE THREAD

**Issue by Mr-zhu0912** [layumi/Pedestrian_Alignment#22]
First of all, thanks a lot for your great source code. 
But I have a question in "resnet52_market_stn_alignment.m" file. dagnn.AffineGridGenerator and dagnn.BilinearSampler correspond to the function name of pytorch . 
I serarch in pytorch documentation but nothing found. would you tell me something about it.Thinks

**Comment by layumi** [comment]
Hi @Mr-zhu0912 
I haven't the experience of SPT in pytorch. So you may check the pytorch tutorial. I think it could help you.
https://pytorch.org/tutorials/intermediate/spatial_transformer_tutorial.html

I think the function names are changed to `affine_grid` and `grid_sample modules`.
Note that we need the latest version of PyTorch that contains affine_grid and grid_sample modules.

**Comment by Mr-zhu0912** [comment]
@layumi
ok . i get it and will query it.  And there is a problem of the same type here in the "resnet52_market_stn_alignment.m" file.
What does it mean about "resnet52_market_stn_res_fine()" in line one"function net = resnet52_market_stn_res_fine()".
In all files,I did not find "resnet52_market_stn_res_fine()" definition.
Is it an API that can be called directly?
Thinks

**Comment by layumi** [comment]
In Matlab, this line means that we define a function called `resnet52_market_stn_res_fine()`, and it will return `net`.
