### ISSUE TITLE
Fail in compilation

### ISSUE THREAD

**Issue by xueyuxiaolang** [layumi/Pedestrian_Alignment#5]
when I uncomment and modify some lines in gpu_compile.m and run it in Matlab. I find error and I don't know how to solve this problem.
`
>>gpu_compile
Error using vl_compilenn
Too many output arguments.

Error in gpu_compile (line 5)
vl_compilenn('enableGpu', true,...`

ps：I have run `vl_testnn('gpu', true)` and show
`
Failure Summary:

     Name                                                                    Failed  Incomplete  Reason(s)
    =======================================================================================================
     nnmnist[dataType=single,device=gpu]/valErrorRate(networkType=dagnn)       X         X       Errored.
    -------------------------------------------------------------------------------------------------------
     nnmnist[dataType=single,device=gpu]/valErrorRate(networkType=simplenn)    X         X       Errored.
    

result = 

  1×1673 TestResult array with properties:

    Name
    Passed
    Failed
    Incomplete
    Duration
    Details

Totals:
   1671 Passed, 2 Failed, 2 Incomplete.
   482.2786 seconds testing time.`

**Comment by ckmessi** [comment]
@xueyuxiaolang Hi, I encountered the same problem as you said. Have you resolved it and how to resolve it? Thanks.

**Comment by layumi** [comment]
No worries. I used vl_testnn and it also output error. 
More importantly, can you run the code without error?
Sometimes gpu/ readjpg will go wrong.

**Comment by ckmessi** [comment]
@layumi Thank you for your reply. 
Actually, it's my first time to code with MatConvnet, so it's a little confusing at first.
Now I am waiting for finishing downloading the data "imagenet-resnet-50-dag.mat", which is so slow from the vlfeat site. After that, I'll try the functional code. Thank your for your share.
