### ISSUE TITLE
Error using vl_nnloss (line 169)

### ISSUE THREAD

**Issue by sde123** [layumi/Pedestrian_Alignment#6]
@layumi 
hello
When I run the train_id_net_res_market_align.m
I got the error:
```
train: epoch 01:   1/367:Error using vl_nnloss (line 169)
Assertion failed.

Error in dagnn.Loss/backward (line 22)
      derInputs{1} = vl_nnloss(inputs{1}, inputs{2}, derOutputs{1}, 'loss', obj.loss, obj.opts{:}) ;

Error in dagnn.Layer/backwardAdvanced (line 120)
      [derInputs, derParams] = obj.backward ...

Error in dagnn.DagNN/eval (line 117)
  obj.layers(l).block.backwardAdvanced(obj.layers(l)) ;

Error in cnn_train_dag2>processEpoch (line 227)
            net.eval(inputs, params.derOutputs, 'holdOn', s < params.numSubBatches) ;

Error in cnn_train_dag2 (line 90)
        [net, state] = processEpoch(net, state, params, 'train',opts) ;

Error in train_id_net_res_market_align (line 32)
[net,info] = cnn_train_dag2(net, imdb, @getBatch,opts) ;
 ```
Could you please tell me what is wrong? thankyou

**Comment by layumi** [comment]
@sde123 
https://github.com/layumi/Pedestrian_Alignment/blob/master/matlab/vl_nnloss.m#L169
The input size does not equal to the label size.
You may set a breakpoint here and check the size of the inputs.
Usually it caused by  the wrong network structure or the data inputs.

**Comment by TaihuLight** [comment]
@sde123 
I use the pre-trained model ResNeXt instead of resnet, and get the same error.
The input size [0,0,1,1,] does not equal to the label size  [1,16,1,1,], but what can do to modify the code in [https://github.com/layumi/Pedestrian_Alignment/blob/master/resnet52_market.m](url)?

**Comment by TaihuLight** [comment]
It may be the input and output params of the certain layer is wrong, especially for the newly add layers. You can check it by looking at net.layers.
