### ISSUE TITLE
I've run through all the step,but the when I ran train_id_net_res_market_align.m  I got a strange result 

### ISSUE THREAD

**Issue by December-boy** [layumi/Pedestrian_Alignment#7]
[net-train.pdf](https://github.com/layumi/Pedestrian_Alignment/files/1394747/net-train.pdf)

**Comment by December-boy** [comment]
I've found out the crux of the problem. I set the batchsize of train_id_net_res_market_align.m to 16 ,then I changed it to 25 and the result is **alpha: 0.500000 single query: mAP = 0.617003, r1 precision = 0.822447**

**Comment by layumi** [comment]
Glad to hear from you.
It is a small trick. Small batch-size can improve the performance about 2%.
I think there is a similar issue with ICLR17 https://openreview.net/forum?id=H1oyRlYgg <https://openreview.net/forum?id=H1oyRlYgg>

If you have any  problem, you can ask me without hesitation. You are welcomed.


Zhedong Zheng
University of Technology Sydney
https://zdzheng.xyz

**Comment by TaihuLight** [comment]
This is an interesting work, and the results of Single-query Result can be obtain by running Run evaluation/zzd_evaluation_res_faster.m.However, how to get the results of multiple Query?
