### ISSUE TITLE
which cuda and cudnn version did you use?

### ISSUE THREAD

**Issue by songh1024** [layumi/Pedestrian_Alignment#8]
@layumi
Hello
When I run the train_id_net_res_market_new.m
I got the error:
Error using vl_nnconv
forward:cuDNN error [cudnn:"../Pedestrain_Alignment/matlab/src/bits/impl/nnconv_cudnn.cu":141(CUDNN_STATUS_BAD_PARAM)]
by the way, which cuda and cudnn version did you use?Any answer will be appreciated.

**Comment by layumi** [comment]
Hi @songh1024 
I use cuda8.0 with cudnn5.1

**Comment by songh1024** [comment]
Thank you for your time.

**Comment by layumi** [comment]
I think cuda7.5(with right version cudnn) also works.

**Comment by songh1024** [comment]
I use cuda8.0 and cudnn5.1, but I got the above error in nnconv_cudnn.cn.

**Comment by layumi** [comment]
Hi @songh1024  
You may try turn off the cudnn first.
